2020-08-11T11:44:07.0460433+08:00|1|INFO|DataSync.Log|Storage folder: D:\unity\BuildCube\BuildCube\BuildCube\Assets\TestData\TestStore successfully validated. 
2020-08-11T11:44:07.0719747+08:00|117|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2020-08-11T11:44:07.1299047+08:00|117|INFO|DataSync.Log|MovedFromStorageToSender. 
2020-08-11T11:44:07.1847562+08:00|117|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2020-08-11T11:44:07.2405760+08:00|117|INFO|DataSync.Log|MovedFromBufferToSender. 
2020-08-11T11:44:37.0827818+08:00|15|INFO|DataSync.Log|SerializationStarted. Items count: 1 
2020-08-11T11:44:37.2071949+08:00|15|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: eb1fc7d46f0847839ae94b84e52316c2(0-0). 
2020-08-11T11:44:37.2131982+08:00|15|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: eb1fc7d46f0847839ae94b84e52316c2(0-0). 
2020-08-11T11:44:39.9785950+08:00|38|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: eb1fc7d46f0847839ae94b84e52316c2(0-0). Message: System.Net.WebException: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ) ---> System.Net.Sockets.SocketException: 無法連線，因為目標電腦拒絕連線。    at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0016d] in <735c83e43c004ee998f77c68cf8035da>:0     --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0003a] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <599589bf4ce248909b8a14cbe4a2034e>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<GetResponseAsync>d__39.MoveNext () [0x00086] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<SendAsync>d__36.MoveNext () [0x0017d] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.TransmissionSender+<StartSending>d__24.MoveNext () [0x000bb] in <20f93252061247f09e8451bed298b761>:0 . 
2020-08-11T11:44:39.9785950+08:00|38|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: eb1fc7d46f0847839ae94b84e52316c2(0-0). Message: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ). StatusCode: 0. Description: . 
2020-08-11T11:46:01.0490192+08:00|11|INFO|DataSync.Log|SerializationStarted. Items count: 1 
2020-08-11T11:46:01.0609900+08:00|11|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: 3ab98fafeb654c748958128586afd46e(1-1). 
2020-08-11T11:46:01.0609900+08:00|11|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: 3ab98fafeb654c748958128586afd46e(1-1). 
2020-08-11T11:50:48.1813737+08:00|1|INFO|DataSync.Log|Storage folder: D:\unity\BuildCube\BuildCube\BuildCube\Assets\TestData\TestStore successfully validated. 
2020-08-11T11:50:48.2172435+08:00|15|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2020-08-11T11:50:48.2761236+08:00|15|INFO|DataSync.Log|MovedFromStorageToSender. 
2020-08-11T11:50:48.3319685+08:00|15|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2020-08-11T11:50:48.3888344+08:00|15|INFO|DataSync.Log|MovedFromBufferToSender. 
2020-08-11T11:51:18.2301197+08:00|15|INFO|DataSync.Log|SerializationStarted. Items count: 1 
2020-08-11T11:51:18.3208452+08:00|15|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: e7820b6cfc264079a9d50ee6b1200592(0-0). 
2020-08-11T11:51:18.3208452+08:00|15|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: e7820b6cfc264079a9d50ee6b1200592(0-0). 
2020-08-11T11:51:21.0547624+08:00|22|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: e7820b6cfc264079a9d50ee6b1200592(0-0). Message: System.Net.WebException: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ) ---> System.Net.Sockets.SocketException: 無法連線，因為目標電腦拒絕連線。    at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0016d] in <735c83e43c004ee998f77c68cf8035da>:0     --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0003a] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <599589bf4ce248909b8a14cbe4a2034e>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<GetResponseAsync>d__39.MoveNext () [0x00086] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<SendAsync>d__36.MoveNext () [0x0017d] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.TransmissionSender+<StartSending>d__24.MoveNext () [0x000bb] in <20f93252061247f09e8451bed298b761>:0 . 
2020-08-11T11:51:21.0547624+08:00|22|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: e7820b6cfc264079a9d50ee6b1200592(0-0). Message: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ). StatusCode: 0. Description: . 
2020-08-11T11:54:58.2955092+08:00|1|INFO|DataSync.Log|Storage folder: D:\unity\BuildCube\BuildCube\BuildCube\Assets\TestData\TestStore successfully validated. 
2020-08-11T11:54:58.3253929+08:00|14|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2020-08-11T11:54:58.4169070+08:00|14|INFO|DataSync.Log|MovedFromStorageToSender. 
2020-08-11T11:54:58.4727916+08:00|14|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2020-08-11T11:54:58.5306029+08:00|14|INFO|DataSync.Log|MovedFromBufferToSender. 
2020-08-11T11:55:28.3361065+08:00|14|INFO|DataSync.Log|SerializationStarted. Items count: 1 
2020-08-11T11:55:28.4258338+08:00|14|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: 9caa131f826c424f8e8eb2efacdd43e9(0-0). 
2020-08-11T11:55:28.4338453+08:00|14|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: 9caa131f826c424f8e8eb2efacdd43e9(0-0). 
2020-08-11T11:55:38.5103533+08:00|14|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 9caa131f826c424f8e8eb2efacdd43e9(0-0). Message: System.Net.WebException: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ) ---> System.Net.Sockets.SocketException: 無法連線，因為目標電腦拒絕連線。    at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0016d] in <735c83e43c004ee998f77c68cf8035da>:0     --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0003a] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <599589bf4ce248909b8a14cbe4a2034e>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<GetResponseAsync>d__39.MoveNext () [0x00086] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<SendAsync>d__36.MoveNext () [0x0017d] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.TransmissionSender+<StartSending>d__24.MoveNext () [0x000bb] in <20f93252061247f09e8451bed298b761>:0 . 
2020-08-11T11:55:38.5103533+08:00|14|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 9caa131f826c424f8e8eb2efacdd43e9(0-0). Message: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ). StatusCode: 0. Description: . 
2020-08-11T11:57:37.3337371+08:00|1|INFO|DataSync.Log|Storage folder: D:\unity\BuildCube\BuildCube\BuildCube\Assets\TestData\TestStore successfully validated. 
2020-08-11T11:57:37.3626579+08:00|24|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2020-08-11T11:57:37.4223968+08:00|24|INFO|DataSync.Log|MovedFromStorageToSender. 
2020-08-11T11:57:37.4782195+08:00|24|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2020-08-11T11:57:37.5370951+08:00|24|INFO|DataSync.Log|MovedFromBufferToSender. 
2020-08-11T11:58:07.3707070+08:00|24|INFO|DataSync.Log|SerializationStarted. Items count: 1 
2020-08-11T11:58:07.4382125+08:00|24|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: f8ce81a977d44b31beafc2941cedf093(0-0). 
2020-08-11T11:58:07.4452270+08:00|24|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: f8ce81a977d44b31beafc2941cedf093(0-0). 
2020-08-11T11:58:16.3471785+08:00|24|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: f8ce81a977d44b31beafc2941cedf093(0-0). Message: System.Net.WebException: Error: ConnectFailure (連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。 ) ---> System.Net.Sockets.SocketException: 連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。    at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0016d] in <735c83e43c004ee998f77c68cf8035da>:0     --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0003a] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <599589bf4ce248909b8a14cbe4a2034e>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<GetResponseAsync>d__39.MoveNext () [0x00086] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<SendAsync>d__36.MoveNext () [0x0017d] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.TransmissionSender+<StartSending>d__24.MoveNext () [0x000bb] in <20f93252061247f09e8451bed298b761>:0 . 
2020-08-11T11:58:16.3591145+08:00|24|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: f8ce81a977d44b31beafc2941cedf093(0-0). Message: Error: ConnectFailure (連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。 ). StatusCode: 0. Description: . 
2020-08-11T11:59:01.4706191+08:00|1|INFO|DataSync.Log|Storage folder: D:\unity\BuildCube\BuildCube\BuildCube\Assets\TestData\TestStore successfully validated. 
2020-08-11T11:59:01.5000822+08:00|36|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2020-08-11T11:59:01.5599173+08:00|36|INFO|DataSync.Log|MovedFromStorageToSender. 
2020-08-11T11:59:01.6207612+08:00|36|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2020-08-11T11:59:01.6775749+08:00|36|INFO|DataSync.Log|MovedFromBufferToSender. 
2020-08-11T11:59:31.5139914+08:00|49|INFO|DataSync.Log|SerializationStarted. Items count: 1 
2020-08-11T11:59:31.5962141+08:00|49|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: 514814756a5b480283387a37399b4a60(0-0). 
2020-08-11T11:59:31.6032285+08:00|49|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: 514814756a5b480283387a37399b4a60(0-0). 
2020-08-11T11:59:34.2998710+08:00|49|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 514814756a5b480283387a37399b4a60(0-0). Message: System.Net.WebException: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ) ---> System.Net.Sockets.SocketException: 無法連線，因為目標電腦拒絕連線。    at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0016d] in <735c83e43c004ee998f77c68cf8035da>:0     --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0003a] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <599589bf4ce248909b8a14cbe4a2034e>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<GetResponseAsync>d__39.MoveNext () [0x00086] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<SendAsync>d__36.MoveNext () [0x0017d] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.TransmissionSender+<StartSending>d__24.MoveNext () [0x000bb] in <20f93252061247f09e8451bed298b761>:0 . 
2020-08-11T11:59:34.3088456+08:00|49|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 514814756a5b480283387a37399b4a60(0-0). Message: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ). StatusCode: 0. Description: . 
2020-08-11T12:06:40.3407298+08:00|1|INFO|DataSync.Log|Storage folder: D:\unity\BuildCube\BuildCube\BuildCube\Assets\TestData\TestStore successfully validated. 
2020-08-11T12:06:40.3746398+08:00|14|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2020-08-11T12:06:40.4335244+08:00|14|INFO|DataSync.Log|MovedFromStorageToSender. 
2020-08-11T12:06:40.4903685+08:00|14|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2020-08-11T12:06:40.5472445+08:00|14|INFO|DataSync.Log|MovedFromBufferToSender. 
2020-08-11T12:07:10.3914756+08:00|18|INFO|DataSync.Log|SerializationStarted. Items count: 1 
2020-08-11T12:07:10.5007010+08:00|18|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: 53b857e2cc7f433daaf37563061a2f01(0-0). 
2020-08-11T12:07:10.5136667+08:00|18|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: 53b857e2cc7f433daaf37563061a2f01(0-0). 
2020-08-11T12:07:17.0019417+08:00|21|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 53b857e2cc7f433daaf37563061a2f01(0-0). Message: System.Net.WebException: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ) ---> System.Net.Sockets.SocketException: 無法連線，因為目標電腦拒絕連線。    at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0016d] in <735c83e43c004ee998f77c68cf8035da>:0     --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0003a] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <599589bf4ce248909b8a14cbe4a2034e>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<GetResponseAsync>d__39.MoveNext () [0x00086] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<SendAsync>d__36.MoveNext () [0x0017d] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.TransmissionSender+<StartSending>d__24.MoveNext () [0x000bb] in <20f93252061247f09e8451bed298b761>:0 . 
2020-08-11T12:07:17.0089223+08:00|21|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 53b857e2cc7f433daaf37563061a2f01(0-0). Message: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ). StatusCode: 0. Description: . 
2020-08-11T12:10:41.8979713+08:00|1|INFO|DataSync.Log|Transmitter flushed telemetry events. 
2020-08-11T12:10:41.8979713+08:00|1|INFO|DataSync.Log|SerializationStarted. Items count: 2 
2020-08-11T12:10:41.9139296+08:00|1|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: 8ea9ba273ad44a80aa6ef2f6413ec0d5(1-2). 
2020-08-11T12:10:41.9139296+08:00|1|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: 8ea9ba273ad44a80aa6ef2f6413ec0d5(1-2). 
2020-08-11T12:10:41.9303951+08:00|1|INFO|DataSync.Log|DataSync.ApplicationLifecycleTransmissionPolicy changed sender capacity to 0 
2020-08-11T12:10:41.9303951+08:00|1|INFO|DataSync.Log|DataSync.ApplicationLifecycleTransmissionPolicy changed buffer capacity to 0 
2020-08-11T12:10:41.9303951+08:00|1|INFO|DataSync.Log|StorageCapacityReset: DataSync.ApplicationLifecycleTransmissionPolicy 
2020-08-11T12:10:41.9513459+08:00|1|WARN|DataSync.Log|BufferEnqueueNoCapacity. Size: 0. Capacity: 0. 
2020-08-11T12:10:41.9513459+08:00|1|INFO|DataSync.Log|MovedFromBufferToStorage. 
2020-08-11T12:10:41.9623161+08:00|1|INFO|DataSync.Log|TransmitterEmptyBuffer 
2020-08-11T12:10:41.9623161+08:00|1|WARN|DataSync.Log|BufferEnqueueNoCapacity. Size: 0. Capacity: 0. 
2020-08-11T12:10:44.5752793+08:00|30|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 8ea9ba273ad44a80aa6ef2f6413ec0d5(1-2). Message: System.Net.WebException: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ) ---> System.Net.Sockets.SocketException: 無法連線，因為目標電腦拒絕連線。    at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0016d] in <735c83e43c004ee998f77c68cf8035da>:0     --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0003a] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <599589bf4ce248909b8a14cbe4a2034e>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<GetResponseAsync>d__39.MoveNext () [0x00086] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<SendAsync>d__36.MoveNext () [0x0017d] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.TransmissionSender+<StartSending>d__24.MoveNext () [0x000bb] in <20f93252061247f09e8451bed298b761>:0 . 
2020-08-11T12:10:44.5842200+08:00|30|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 8ea9ba273ad44a80aa6ef2f6413ec0d5(1-2). Message: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ). StatusCode: 0. Description: . 
2020-08-11T12:10:44.5842200+08:00|30|WARN|DataSync.Log|SenderEnqueueNoCapacity. TransmissionCount: 0. Capacity: 0. 
2020-08-13T10:56:39.6525216+08:00|1|INFO|DataSync.Log|Storage folder: D:\Projects\BuildCube\BuildCube\Assets\TestData\TestStore successfully validated. 
2020-08-13T10:56:39.6914178+08:00|287|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2020-08-13T10:56:39.7532518+08:00|287|INFO|DataSync.Log|MovedFromStorageToSender. 
2020-08-13T10:56:39.8180796+08:00|287|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2020-08-13T10:56:39.8789165+08:00|287|INFO|DataSync.Log|MovedFromBufferToSender. 
2020-08-13T10:57:09.7094762+08:00|48|INFO|DataSync.Log|SerializationStarted. Items count: 1 
2020-08-13T10:57:09.9548209+08:00|48|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: defd5e2ed5a040d7b2396d51313164a5(0-0). 
2020-08-13T10:57:10.0116689+08:00|48|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: defd5e2ed5a040d7b2396d51313164a5(0-0). 
2020-08-13T10:57:14.8044132+08:00|286|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: defd5e2ed5a040d7b2396d51313164a5(0-0). Message: System.Net.WebException: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ) ---> System.Net.Sockets.SocketException: 無法連線，因為目標電腦拒絕連線。    at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0016d] in <735c83e43c004ee998f77c68cf8035da>:0     --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0003a] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <599589bf4ce248909b8a14cbe4a2034e>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<GetResponseAsync>d__39.MoveNext () [0x00086] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<SendAsync>d__36.MoveNext () [0x0017d] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.TransmissionSender+<StartSending>d__24.MoveNext () [0x000bb] in <20f93252061247f09e8451bed298b761>:0 . 
2020-08-13T10:57:14.8193726+08:00|286|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: defd5e2ed5a040d7b2396d51313164a5(0-0). Message: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ). StatusCode: 0. Description: . 
2020-08-13T10:57:45.0109762+08:00|1|INFO|DataSync.Log|Storage folder: D:\Projects\BuildCube\BuildCube\Assets\TestData\TestStore successfully validated. 
2020-08-13T10:57:45.0508706+08:00|49|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2020-08-13T10:57:45.1231863+08:00|49|INFO|DataSync.Log|MovedFromStorageToSender. 
2020-08-13T10:57:45.2069664+08:00|49|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2020-08-13T10:57:45.2707959+08:00|49|INFO|DataSync.Log|MovedFromBufferToSender. 
2020-08-13T10:58:15.0637881+08:00|286|INFO|DataSync.Log|SerializationStarted. Items count: 1 
2020-08-13T10:58:15.1734944+08:00|286|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: cefef944d49b44f58f850bf8af99a5d2(0-0). 
2020-08-13T10:58:15.2054095+08:00|286|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: cefef944d49b44f58f850bf8af99a5d2(0-0). 
2020-08-13T10:58:25.6528333+08:00|44|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: cefef944d49b44f58f850bf8af99a5d2(0-0). Message: System.Net.WebException: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ) ---> System.Net.Sockets.SocketException: 無法連線，因為目標電腦拒絕連線。    at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0016d] in <735c83e43c004ee998f77c68cf8035da>:0     --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0003a] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <599589bf4ce248909b8a14cbe4a2034e>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<GetResponseAsync>d__39.MoveNext () [0x00086] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<SendAsync>d__36.MoveNext () [0x0017d] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.TransmissionSender+<StartSending>d__24.MoveNext () [0x000bb] in <20f93252061247f09e8451bed298b761>:0 . 
2020-08-13T10:58:25.6657993+08:00|44|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: cefef944d49b44f58f850bf8af99a5d2(0-0). Message: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ). StatusCode: 0. Description: . 
2020-08-13T10:58:37.9846839+08:00|1|INFO|DataSync.Log|Transmitter flushed telemetry events. 
2020-08-13T10:58:38.0225843+08:00|1|INFO|DataSync.Log|SerializationStarted. Items count: 2 
2020-08-13T10:58:38.0754421+08:00|1|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: 49c5ebcfc7d94468b0e511a00efba8b3(1-2). 
2020-08-13T10:58:38.1711868+08:00|1|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: 49c5ebcfc7d94468b0e511a00efba8b3(1-2). 
2020-08-13T10:58:38.2090849+08:00|1|INFO|DataSync.Log|DataSync.ApplicationLifecycleTransmissionPolicy changed sender capacity to 0 
2020-08-13T10:58:38.2509727+08:00|1|INFO|DataSync.Log|DataSync.ApplicationLifecycleTransmissionPolicy changed buffer capacity to 0 
2020-08-13T10:58:38.2699220+08:00|1|INFO|DataSync.Log|StorageCapacityReset: DataSync.ApplicationLifecycleTransmissionPolicy 
2020-08-13T10:58:38.2848822+08:00|1|WARN|DataSync.Log|BufferEnqueueNoCapacity. Size: 0. Capacity: 0. 
2020-08-13T10:58:38.3058259+08:00|1|INFO|DataSync.Log|MovedFromBufferToStorage. 
2020-08-13T10:58:38.3138043+08:00|1|INFO|DataSync.Log|TransmitterEmptyBuffer 
2020-08-13T10:58:38.3138043+08:00|1|WARN|DataSync.Log|BufferEnqueueNoCapacity. Size: 0. Capacity: 0. 
2020-08-13T10:58:41.2702026+08:00|286|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 49c5ebcfc7d94468b0e511a00efba8b3(1-2). Message: System.Net.WebException: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ) ---> System.Net.Sockets.SocketException: 無法連線，因為目標電腦拒絕連線。    at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0016d] in <735c83e43c004ee998f77c68cf8035da>:0     --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0003a] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <599589bf4ce248909b8a14cbe4a2034e>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<GetResponseAsync>d__39.MoveNext () [0x00086] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<SendAsync>d__36.MoveNext () [0x0017d] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.TransmissionSender+<StartSending>d__24.MoveNext () [0x000bb] in <20f93252061247f09e8451bed298b761>:0 . 
2020-08-13T10:58:41.2702026+08:00|286|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 49c5ebcfc7d94468b0e511a00efba8b3(1-2). Message: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ). StatusCode: 0. Description: . 
2020-08-13T10:58:41.2901492+08:00|286|WARN|DataSync.Log|SenderEnqueueNoCapacity. TransmissionCount: 0. Capacity: 0. 
2020-08-13T11:08:45.4157459+08:00|1|INFO|DataSync.Log|Storage folder: D:\Projects\BuildCube\BuildCube\Assets\TestData\TestStore successfully validated. 
2020-08-13T11:08:45.4526480+08:00|45|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2020-08-13T11:08:45.5154801+08:00|45|INFO|DataSync.Log|MovedFromStorageToSender. 
2020-08-13T11:08:45.5773143+08:00|45|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2020-08-13T11:08:45.6406525+08:00|45|INFO|DataSync.Log|MovedFromBufferToSender. 
2020-08-13T11:09:15.4655128+08:00|46|INFO|DataSync.Log|SerializationStarted. Items count: 1 
2020-08-13T11:09:15.5512841+08:00|46|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: a4b70f94483c4cb19597afeefffc35e0(0-0). 
2020-08-13T11:09:15.5772146+08:00|46|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: a4b70f94483c4cb19597afeefffc35e0(0-0). 
2020-08-13T11:09:18.9174790+08:00|48|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: a4b70f94483c4cb19597afeefffc35e0(0-0). Message: System.Net.WebException: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ) ---> System.Net.Sockets.SocketException: 無法連線，因為目標電腦拒絕連線。    at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0016d] in <735c83e43c004ee998f77c68cf8035da>:0     --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0003a] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <599589bf4ce248909b8a14cbe4a2034e>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<GetResponseAsync>d__39.MoveNext () [0x00086] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<SendAsync>d__36.MoveNext () [0x0017d] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.TransmissionSender+<StartSending>d__24.MoveNext () [0x000bb] in <20f93252061247f09e8451bed298b761>:0 . 
2020-08-13T11:09:18.9274517+08:00|48|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: a4b70f94483c4cb19597afeefffc35e0(0-0). Message: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ). StatusCode: 0. Description: . 
2020-08-13T11:10:02.5971028+08:00|1|INFO|DataSync.Log|Transmitter flushed telemetry events. 
2020-08-13T11:10:02.6120612+08:00|1|INFO|DataSync.Log|SerializationStarted. Items count: 2 
2020-08-13T11:10:02.6350001+08:00|1|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: 11cd169607454e5dad5db2eb8433301c(1-2). 
2020-08-13T11:10:02.6479653+08:00|1|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: 11cd169607454e5dad5db2eb8433301c(1-2). 
2020-08-13T11:10:02.6778854+08:00|1|INFO|DataSync.Log|DataSync.ApplicationLifecycleTransmissionPolicy changed sender capacity to 0 
2020-08-13T11:10:02.6888563+08:00|1|INFO|DataSync.Log|DataSync.ApplicationLifecycleTransmissionPolicy changed buffer capacity to 0 
2020-08-13T11:10:02.6888563+08:00|1|INFO|DataSync.Log|StorageCapacityReset: DataSync.ApplicationLifecycleTransmissionPolicy 
2020-08-13T11:10:02.7187766+08:00|1|WARN|DataSync.Log|BufferEnqueueNoCapacity. Size: 0. Capacity: 0. 
2020-08-13T11:10:02.7347337+08:00|1|INFO|DataSync.Log|MovedFromBufferToStorage. 
2020-08-13T11:10:02.7486963+08:00|1|INFO|DataSync.Log|TransmitterEmptyBuffer 
2020-08-13T11:10:02.7486963+08:00|1|WARN|DataSync.Log|BufferEnqueueNoCapacity. Size: 0. Capacity: 0. 
2020-08-13T11:10:06.0171008+08:00|44|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 11cd169607454e5dad5db2eb8433301c(1-2). Message: System.Net.WebException: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ) ---> System.Net.Sockets.SocketException: 無法連線，因為目標電腦拒絕連線。    at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0016d] in <735c83e43c004ee998f77c68cf8035da>:0     --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0003a] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <599589bf4ce248909b8a14cbe4a2034e>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<GetResponseAsync>d__39.MoveNext () [0x00086] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<SendAsync>d__36.MoveNext () [0x0017d] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.TransmissionSender+<StartSending>d__24.MoveNext () [0x000bb] in <20f93252061247f09e8451bed298b761>:0 . 
2020-08-13T11:10:06.0171008+08:00|44|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 11cd169607454e5dad5db2eb8433301c(1-2). Message: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ). StatusCode: 0. Description: . 
2020-08-13T11:10:06.0440299+08:00|44|WARN|DataSync.Log|SenderEnqueueNoCapacity. TransmissionCount: 0. Capacity: 0. 
2020-08-13T11:16:47.0949243+08:00|1|INFO|DataSync.Log|Storage folder: D:\Projects\BuildCube\BuildCube\Assets\TestData\TestStore successfully validated. 
2020-08-13T11:16:47.1318263+08:00|287|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2020-08-13T11:16:47.1949249+08:00|287|INFO|DataSync.Log|MovedFromStorageToSender. 
2020-08-13T11:16:47.2627436+08:00|287|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2020-08-13T11:16:47.3268401+08:00|287|INFO|DataSync.Log|MovedFromBufferToSender. 
2020-08-13T11:17:17.1434496+08:00|287|INFO|DataSync.Log|SerializationStarted. Items count: 1 
2020-08-13T11:17:17.2426946+08:00|287|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: 51ce1142373a435bbcbefab49b32f04c(0-0). 
2020-08-13T11:17:17.2696217+08:00|287|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: 51ce1142373a435bbcbefab49b32f04c(0-0). 
2020-08-13T11:17:27.6788253+08:00|285|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 51ce1142373a435bbcbefab49b32f04c(0-0). Message: System.Net.WebException: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ) ---> System.Net.Sockets.SocketException: 無法連線，因為目標電腦拒絕連線。    at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0016d] in <735c83e43c004ee998f77c68cf8035da>:0     --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0003a] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <599589bf4ce248909b8a14cbe4a2034e>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<GetResponseAsync>d__39.MoveNext () [0x00086] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<SendAsync>d__36.MoveNext () [0x0017d] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.TransmissionSender+<StartSending>d__24.MoveNext () [0x000bb] in <20f93252061247f09e8451bed298b761>:0 . 
2020-08-13T11:17:27.6887973+08:00|285|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 51ce1142373a435bbcbefab49b32f04c(0-0). Message: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ). StatusCode: 0. Description: . 
2020-08-13T11:17:32.6183721+08:00|1|INFO|DataSync.Log|Transmitter flushed telemetry events. 
2020-08-13T11:17:32.6283448+08:00|1|INFO|DataSync.Log|SerializationStarted. Items count: 2 
2020-08-13T11:17:32.6452993+08:00|1|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: e7364cc7c2a7400fbba5c434795712a0(1-2). 
2020-08-13T11:17:32.6452993+08:00|1|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: e7364cc7c2a7400fbba5c434795712a0(1-2). 
2020-08-13T11:17:32.6692358+08:00|1|INFO|DataSync.Log|DataSync.ApplicationLifecycleTransmissionPolicy changed sender capacity to 0 
2020-08-13T11:17:32.6971826+08:00|1|INFO|DataSync.Log|DataSync.ApplicationLifecycleTransmissionPolicy changed buffer capacity to 0 
2020-08-13T11:17:32.7051731+08:00|1|INFO|DataSync.Log|StorageCapacityReset: DataSync.ApplicationLifecycleTransmissionPolicy 
2020-08-13T11:17:32.7051731+08:00|1|WARN|DataSync.Log|BufferEnqueueNoCapacity. Size: 0. Capacity: 0. 
2020-08-13T11:17:32.7221282+08:00|1|INFO|DataSync.Log|MovedFromBufferToStorage. 
2020-08-13T11:17:32.7221282+08:00|1|INFO|DataSync.Log|TransmitterEmptyBuffer 
2020-08-13T11:17:32.7480590+08:00|1|WARN|DataSync.Log|BufferEnqueueNoCapacity. Size: 0. Capacity: 0. 
2020-08-13T11:17:42.9938558+08:00|287|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: e7364cc7c2a7400fbba5c434795712a0(1-2). Message: System.Net.WebException: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ) ---> System.Net.Sockets.SocketException: 無法連線，因為目標電腦拒絕連線。    at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0016d] in <735c83e43c004ee998f77c68cf8035da>:0     --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0003a] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <599589bf4ce248909b8a14cbe4a2034e>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<GetResponseAsync>d__39.MoveNext () [0x00086] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<SendAsync>d__36.MoveNext () [0x0017d] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.TransmissionSender+<StartSending>d__24.MoveNext () [0x000bb] in <20f93252061247f09e8451bed298b761>:0 . 
2020-08-13T11:17:43.0038275+08:00|287|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: e7364cc7c2a7400fbba5c434795712a0(1-2). Message: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ). StatusCode: 0. Description: . 
2020-08-13T11:17:43.0397330+08:00|287|WARN|DataSync.Log|SenderEnqueueNoCapacity. TransmissionCount: 0. Capacity: 0. 
2020-08-13T11:19:02.9176471+08:00|1|INFO|DataSync.Log|Storage folder: D:\Projects\BuildCube\BuildCube\Assets\TestData\TestStore successfully validated. 
2020-08-13T11:19:02.9555461+08:00|48|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2020-08-13T11:19:03.0263564+08:00|48|INFO|DataSync.Log|MovedFromStorageToSender. 
2020-08-13T11:19:03.0951732+08:00|48|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2020-08-13T11:19:03.1580042+08:00|48|INFO|DataSync.Log|MovedFromBufferToSender. 
2020-08-13T11:19:32.9687630+08:00|48|INFO|DataSync.Log|SerializationStarted. Items count: 1 
2020-08-13T11:19:33.0824592+08:00|48|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: 8e9ee52c3757467abf9f9165f74908b0(0-0). 
2020-08-13T11:19:33.1133777+08:00|48|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: 8e9ee52c3757467abf9f9165f74908b0(0-0). 
2020-08-13T11:19:36.3588187+08:00|285|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 8e9ee52c3757467abf9f9165f74908b0(0-0). Message: System.Net.WebException: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ) ---> System.Net.Sockets.SocketException: 無法連線，因為目標電腦拒絕連線。    at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0016d] in <735c83e43c004ee998f77c68cf8035da>:0     --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0003a] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <599589bf4ce248909b8a14cbe4a2034e>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<GetResponseAsync>d__39.MoveNext () [0x00086] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<SendAsync>d__36.MoveNext () [0x0017d] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.TransmissionSender+<StartSending>d__24.MoveNext () [0x000bb] in <20f93252061247f09e8451bed298b761>:0 . 
2020-08-13T11:19:36.3817574+08:00|285|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 8e9ee52c3757467abf9f9165f74908b0(0-0). Message: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ). StatusCode: 0. Description: . 
2020-08-13T11:21:02.2869397+08:00|1|INFO|DataSync.Log|Transmitter flushed telemetry events. 
2020-08-13T11:21:02.2989087+08:00|1|INFO|DataSync.Log|SerializationStarted. Items count: 2 
2020-08-13T11:21:02.3128704+08:00|1|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: 8eeee659ca594362b89bba839a5f6570(1-2). 
2020-08-13T11:21:02.3128704+08:00|1|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: 8eeee659ca594362b89bba839a5f6570(1-2). 
2020-08-13T11:21:02.3358097+08:00|1|INFO|DataSync.Log|DataSync.ApplicationLifecycleTransmissionPolicy changed sender capacity to 0 
2020-08-13T11:21:02.3457823+08:00|1|INFO|DataSync.Log|DataSync.ApplicationLifecycleTransmissionPolicy changed buffer capacity to 0 
2020-08-13T11:21:02.3607420+08:00|1|INFO|DataSync.Log|StorageCapacityReset: DataSync.ApplicationLifecycleTransmissionPolicy 
2020-08-13T11:21:02.3737080+08:00|1|WARN|DataSync.Log|BufferEnqueueNoCapacity. Size: 0. Capacity: 0. 
2020-08-13T11:21:02.3737080+08:00|1|INFO|DataSync.Log|MovedFromBufferToStorage. 
2020-08-13T11:21:02.3946520+08:00|1|INFO|DataSync.Log|TransmitterEmptyBuffer 
2020-08-13T11:21:02.4066201+08:00|1|WARN|DataSync.Log|BufferEnqueueNoCapacity. Size: 0. Capacity: 0. 
2020-08-13T11:21:05.7092161+08:00|324|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 8eeee659ca594362b89bba839a5f6570(1-2). Message: System.Net.WebException: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ) ---> System.Net.Sockets.SocketException: 無法連線，因為目標電腦拒絕連線。    at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0016d] in <735c83e43c004ee998f77c68cf8035da>:0     --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0003a] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <599589bf4ce248909b8a14cbe4a2034e>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<GetResponseAsync>d__39.MoveNext () [0x00086] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<SendAsync>d__36.MoveNext () [0x0017d] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.TransmissionSender+<StartSending>d__24.MoveNext () [0x000bb] in <20f93252061247f09e8451bed298b761>:0 . 
2020-08-13T11:21:05.7181916+08:00|324|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 8eeee659ca594362b89bba839a5f6570(1-2). Message: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ). StatusCode: 0. Description: . 
2020-08-13T11:21:05.7181916+08:00|324|WARN|DataSync.Log|SenderEnqueueNoCapacity. TransmissionCount: 0. Capacity: 0. 
2020-08-13T11:23:07.0421329+08:00|1|INFO|DataSync.Log|Storage folder: D:\Projects\BuildCube\BuildCube\Assets\TestData\TestStore successfully validated. 
2020-08-13T11:23:07.0820270+08:00|44|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2020-08-13T11:23:07.1418664+08:00|44|INFO|DataSync.Log|MovedFromStorageToSender. 
2020-08-13T11:23:07.2056957+08:00|44|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2020-08-13T11:23:07.2725167+08:00|44|INFO|DataSync.Log|MovedFromBufferToSender. 
2020-08-13T11:23:37.0978265+08:00|45|INFO|DataSync.Log|SerializationStarted. Items count: 1 
2020-08-13T11:23:37.2125203+08:00|45|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: c680d088ba374d0885f0c506504d6545(0-0). 
2020-08-13T11:23:37.2324661+08:00|45|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: c680d088ba374d0885f0c506504d6545(0-0). 
2020-08-13T11:23:40.7253336+08:00|285|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: c680d088ba374d0885f0c506504d6545(0-0). Message: System.Net.WebException: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ) ---> System.Net.Sockets.SocketException: 無法連線，因為目標電腦拒絕連線。    at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0016d] in <735c83e43c004ee998f77c68cf8035da>:0     --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0003a] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <599589bf4ce248909b8a14cbe4a2034e>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<GetResponseAsync>d__39.MoveNext () [0x00086] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<SendAsync>d__36.MoveNext () [0x0017d] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.TransmissionSender+<StartSending>d__24.MoveNext () [0x000bb] in <20f93252061247f09e8451bed298b761>:0 . 
2020-08-13T11:23:40.7422888+08:00|285|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: c680d088ba374d0885f0c506504d6545(0-0). Message: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ). StatusCode: 0. Description: . 
2020-08-13T11:24:09.1841822+08:00|1|INFO|DataSync.Log|Transmitter flushed telemetry events. 
2020-08-13T11:24:09.1961513+08:00|1|INFO|DataSync.Log|SerializationStarted. Items count: 2 
2020-08-13T11:24:09.2101131+08:00|1|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: 01f9e33b583c4ddebbc81490ed1445ce(1-2). 
2020-08-13T11:24:09.2200863+08:00|1|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: 01f9e33b583c4ddebbc81490ed1445ce(1-2). 
2020-08-13T11:24:09.2200863+08:00|1|INFO|DataSync.Log|DataSync.ApplicationLifecycleTransmissionPolicy changed sender capacity to 0 
2020-08-13T11:24:09.2400329+08:00|1|INFO|DataSync.Log|DataSync.ApplicationLifecycleTransmissionPolicy changed buffer capacity to 0 
2020-08-13T11:24:09.2769345+08:00|1|INFO|DataSync.Log|StorageCapacityReset: DataSync.ApplicationLifecycleTransmissionPolicy 
2020-08-13T11:24:09.2859308+08:00|1|WARN|DataSync.Log|BufferEnqueueNoCapacity. Size: 0. Capacity: 0. 
2020-08-13T11:24:09.3028653+08:00|1|INFO|DataSync.Log|MovedFromBufferToStorage. 
2020-08-13T11:24:09.3138370+08:00|1|INFO|DataSync.Log|TransmitterEmptyBuffer 
2020-08-13T11:24:09.3307899+08:00|1|WARN|DataSync.Log|BufferEnqueueNoCapacity. Size: 0. Capacity: 0. 
2020-08-13T11:24:18.2570325+08:00|44|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 01f9e33b583c4ddebbc81490ed1445ce(1-2). Message: System.Net.WebException: Error: ConnectFailure (連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。 ) ---> System.Net.Sockets.SocketException: 連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。    at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0016d] in <735c83e43c004ee998f77c68cf8035da>:0     --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0003a] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <599589bf4ce248909b8a14cbe4a2034e>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<GetResponseAsync>d__39.MoveNext () [0x00086] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<SendAsync>d__36.MoveNext () [0x0017d] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.TransmissionSender+<StartSending>d__24.MoveNext () [0x000bb] in <20f93252061247f09e8451bed298b761>:0 . 
2020-08-13T11:24:18.2660094+08:00|44|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 01f9e33b583c4ddebbc81490ed1445ce(1-2). Message: Error: ConnectFailure (連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。 ). StatusCode: 0. Description: . 
2020-08-13T11:24:18.2660094+08:00|44|WARN|DataSync.Log|SenderEnqueueNoCapacity. TransmissionCount: 0. Capacity: 0. 
2020-08-13T11:25:08.6058084+08:00|1|INFO|DataSync.Log|Storage folder: D:\Projects\BuildCube\BuildCube\Assets\TestData\TestStore successfully validated. 
2020-08-13T11:25:08.6457025+08:00|45|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2020-08-13T11:25:08.7145177+08:00|45|INFO|DataSync.Log|MovedFromStorageToSender. 
2020-08-13T11:25:08.7962996+08:00|45|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2020-08-13T11:25:08.8616324+08:00|45|INFO|DataSync.Log|MovedFromBufferToSender. 
2020-08-13T11:25:40.9101887+08:00|324|INFO|DataSync.Log|SerializationStarted. Items count: 1 
2020-08-13T11:25:41.0218903+08:00|324|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: d45f469c3b294c3190bc46531db7b9b9(0-0). 
2020-08-13T11:25:41.0742618+08:00|324|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: d45f469c3b294c3190bc46531db7b9b9(0-0). 
2020-08-13T11:25:47.3083611+08:00|1|INFO|DataSync.Log|Transmitter flushed telemetry events. 
2020-08-13T11:25:47.3213263+08:00|1|INFO|DataSync.Log|SerializationStarted. Items count: 2 
2020-08-13T11:25:47.3382810+08:00|1|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: adb394a8643346ceb4c6f8fd77e3f19c(1-2). 
2020-08-13T11:25:47.3482546+08:00|1|WARN|DataSync.Log|SenderEnqueueNoCapacity. TransmissionCount: 1. Capacity: 1. 
2020-08-13T11:25:47.3582274+08:00|1|INFO|DataSync.Log|TransmitterSenderSkipped. TransmissionId: adb394a8643346ceb4c6f8fd77e3f19c(1-2). 
2020-08-13T11:25:47.3731878+08:00|1|INFO|DataSync.Log|BufferEnqueued. TransmissionId: adb394a8643346ceb4c6f8fd77e3f19c(1-2). TransmissionCount: 1. 
2020-08-13T11:25:47.3731878+08:00|1|INFO|DataSync.Log|DataSync.ApplicationLifecycleTransmissionPolicy changed sender capacity to 0 
2020-08-13T11:25:47.3981207+08:00|1|INFO|DataSync.Log|DataSync.ApplicationLifecycleTransmissionPolicy changed buffer capacity to 0 
2020-08-13T11:25:47.4070968+08:00|1|INFO|DataSync.Log|StorageCapacityReset: DataSync.ApplicationLifecycleTransmissionPolicy 
2020-08-13T11:25:47.4200623+08:00|1|WARN|DataSync.Log|BufferEnqueueNoCapacity. Size: 0. Capacity: 0. 
2020-08-13T11:25:47.4599563+08:00|1|INFO|DataSync.Log|TransmissionSavedToStorage. TransmissionId: adb394a8643346ceb4c6f8fd77e3f19c(1-2). 
2020-08-13T11:25:47.4739193+08:00|1|WARN|DataSync.Log|BufferEnqueueNoCapacity. Size: 0. Capacity: 0. 
2020-08-13T11:25:47.4739193+08:00|1|INFO|DataSync.Log|MovedFromBufferToStorage. 
2020-08-13T11:25:47.4888791+08:00|1|INFO|DataSync.Log|TransmitterEmptyBuffer 
2020-08-13T11:25:47.4888791+08:00|1|WARN|DataSync.Log|BufferEnqueueNoCapacity. Size: 0. Capacity: 0. 
2020-08-13T11:25:48.8899629+08:00|285|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: d45f469c3b294c3190bc46531db7b9b9(0-0). Message: System.Net.WebException: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ) ---> System.Net.Sockets.SocketException: 無法連線，因為目標電腦拒絕連線。    at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0016d] in <735c83e43c004ee998f77c68cf8035da>:0     --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0003a] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <599589bf4ce248909b8a14cbe4a2034e>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<GetResponseAsync>d__39.MoveNext () [0x00086] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<SendAsync>d__36.MoveNext () [0x0017d] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.TransmissionSender+<StartSending>d__24.MoveNext () [0x000bb] in <20f93252061247f09e8451bed298b761>:0 . 
2020-08-13T11:25:48.8899629+08:00|285|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: d45f469c3b294c3190bc46531db7b9b9(0-0). Message: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ). StatusCode: 0. Description: . 
2020-08-13T11:25:48.9099091+08:00|285|WARN|DataSync.Log|SenderEnqueueNoCapacity. TransmissionCount: 0. Capacity: 0. 
2020-08-13T11:29:03.7502668+08:00|1|INFO|DataSync.Log|Storage folder: D:\Projects\BuildCube\BuildCube\Assets\TestData\TestStore successfully validated. 
2020-08-13T11:29:03.7901603+08:00|325|INFO|DataSync.Log|StorageSize. StorageSize: 406. 
2020-08-13T11:29:03.8709442+08:00|325|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: eb0e4382d0704b7a97ca78949f4275ee. 
2020-08-13T11:29:03.9417548+08:00|325|WARN|DataSync.Log|SenderEnqueueNoCapacity. TransmissionCount: 1. Capacity: 1. 
2020-08-13T11:29:03.9527258+08:00|325|INFO|DataSync.Log|MovedFromStorageToSender. 
2020-08-13T11:29:04.0165549+08:00|325|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2020-08-13T11:29:04.0165549+08:00|325|WARN|DataSync.Log|SenderEnqueueNoCapacity. TransmissionCount: 1. Capacity: 1. 
2020-08-13T11:29:04.0374992+08:00|325|INFO|DataSync.Log|MovedFromBufferToSender. 
2020-08-13T11:29:20.1233513+08:00|285|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: eb0e4382d0704b7a97ca78949f4275ee. Message: System.Net.WebException: Error: ConnectFailure (連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。 ) ---> System.Net.Sockets.SocketException: 連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。    at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0016d] in <735c83e43c004ee998f77c68cf8035da>:0     --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0003a] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <599589bf4ce248909b8a14cbe4a2034e>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<GetResponseAsync>d__39.MoveNext () [0x00086] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<SendAsync>d__36.MoveNext () [0x0017d] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.TransmissionSender+<StartSending>d__24.MoveNext () [0x000bb] in <20f93252061247f09e8451bed298b761>:0 . 
2020-08-13T11:29:20.1393096+08:00|285|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: eb0e4382d0704b7a97ca78949f4275ee. Message: Error: ConnectFailure (連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。 ). StatusCode: 0. Description: . 
2020-08-13T11:29:33.8062236+08:00|45|INFO|DataSync.Log|SerializationStarted. Items count: 1 
2020-08-13T11:29:33.8969818+08:00|45|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: 054d03341f9841a5adc95503289e353a(0-0). 
2020-08-13T11:29:33.9189236+08:00|45|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: 054d03341f9841a5adc95503289e353a(0-0). 
2020-08-13T11:29:37.3029809+08:00|44|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 054d03341f9841a5adc95503289e353a(0-0). Message: System.Net.WebException: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ) ---> System.Net.Sockets.SocketException: 無法連線，因為目標電腦拒絕連線。    at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0016d] in <735c83e43c004ee998f77c68cf8035da>:0     --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0003a] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <599589bf4ce248909b8a14cbe4a2034e>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<GetResponseAsync>d__39.MoveNext () [0x00086] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<SendAsync>d__36.MoveNext () [0x0017d] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.TransmissionSender+<StartSending>d__24.MoveNext () [0x000bb] in <20f93252061247f09e8451bed298b761>:0 . 
2020-08-13T11:29:37.3129548+08:00|44|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 054d03341f9841a5adc95503289e353a(0-0). Message: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ). StatusCode: 0. Description: . 
2020-08-13T11:29:47.4051099+08:00|1|INFO|DataSync.Log|Transmitter flushed telemetry events. 
2020-08-13T11:29:47.4240590+08:00|1|INFO|DataSync.Log|SerializationStarted. Items count: 2 
2020-08-13T11:29:47.4410142+08:00|1|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: bc7637f02bd34ccf884ae46c0c866458(1-2). 
2020-08-13T11:29:47.4410142+08:00|1|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: bc7637f02bd34ccf884ae46c0c866458(1-2). 
2020-08-13T11:29:47.4649507+08:00|1|INFO|DataSync.Log|DataSync.ApplicationLifecycleTransmissionPolicy changed sender capacity to 0 
2020-08-13T11:29:47.4888858+08:00|1|INFO|DataSync.Log|DataSync.ApplicationLifecycleTransmissionPolicy changed buffer capacity to 0 
2020-08-13T11:29:47.4888858+08:00|1|INFO|DataSync.Log|StorageCapacityReset: DataSync.ApplicationLifecycleTransmissionPolicy 
2020-08-13T11:29:47.5128221+08:00|1|WARN|DataSync.Log|BufferEnqueueNoCapacity. Size: 0. Capacity: 0. 
2020-08-13T11:29:47.5208007+08:00|1|INFO|DataSync.Log|MovedFromBufferToStorage. 
2020-08-13T11:29:47.5307740+08:00|1|INFO|DataSync.Log|TransmitterEmptyBuffer 
2020-08-13T11:29:47.5487258+08:00|1|WARN|DataSync.Log|BufferEnqueueNoCapacity. Size: 0. Capacity: 0. 
2020-08-13T11:29:50.5833262+08:00|45|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: bc7637f02bd34ccf884ae46c0c866458(1-2). Message: System.Net.WebException: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ) ---> System.Net.Sockets.SocketException: 無法連線，因為目標電腦拒絕連線。    at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0016d] in <735c83e43c004ee998f77c68cf8035da>:0     --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0003a] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <599589bf4ce248909b8a14cbe4a2034e>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<GetResponseAsync>d__39.MoveNext () [0x00086] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<SendAsync>d__36.MoveNext () [0x0017d] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.TransmissionSender+<StartSending>d__24.MoveNext () [0x000bb] in <20f93252061247f09e8451bed298b761>:0 . 
2020-08-13T11:29:50.5923024+08:00|45|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: bc7637f02bd34ccf884ae46c0c866458(1-2). Message: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ). StatusCode: 0. Description: . 
2020-08-13T11:29:50.5923024+08:00|45|WARN|DataSync.Log|SenderEnqueueNoCapacity. TransmissionCount: 0. Capacity: 0. 
2020-08-13T11:34:07.4771385+08:00|1|INFO|DataSync.Log|Storage folder: D:\Projects\BuildCube\BuildCube\Assets\TestData\TestStore successfully validated. 
2020-08-13T11:34:07.5200239+08:00|324|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2020-08-13T11:34:07.5869444+08:00|324|INFO|DataSync.Log|MovedFromStorageToSender. 
2020-08-13T11:34:07.6501040+08:00|324|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2020-08-13T11:34:07.7119392+08:00|324|INFO|DataSync.Log|MovedFromBufferToSender. 
2020-08-13T11:34:21.0712644+08:00|1|INFO|DataSync.Log|Transmitter flushed telemetry events. 
2020-08-13T11:34:21.0852266+08:00|1|INFO|DataSync.Log|SerializationStarted. Items count: 3 
2020-08-13T11:34:21.1340956+08:00|1|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: e8b306d171dd4c6eb6c73762589a07fb(0-2). 
2020-08-13T11:34:21.1600264+08:00|1|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: e8b306d171dd4c6eb6c73762589a07fb(0-2). 
2020-08-13T11:34:21.2118881+08:00|1|INFO|DataSync.Log|DataSync.ApplicationLifecycleTransmissionPolicy changed sender capacity to 0 
2020-08-13T11:34:21.2318339+08:00|1|INFO|DataSync.Log|DataSync.ApplicationLifecycleTransmissionPolicy changed buffer capacity to 0 
2020-08-13T11:34:21.2398129+08:00|1|INFO|DataSync.Log|StorageCapacityReset: DataSync.ApplicationLifecycleTransmissionPolicy 
2020-08-13T11:34:21.2398129+08:00|1|WARN|DataSync.Log|BufferEnqueueNoCapacity. Size: 0. Capacity: 0. 
2020-08-13T11:34:21.2557707+08:00|1|INFO|DataSync.Log|MovedFromBufferToStorage. 
2020-08-13T11:34:21.2637489+08:00|1|INFO|DataSync.Log|TransmitterEmptyBuffer 
2020-08-13T11:34:21.2637489+08:00|1|WARN|DataSync.Log|BufferEnqueueNoCapacity. Size: 0. Capacity: 0. 
2020-08-13T11:34:34.8911972+08:00|366|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: e8b306d171dd4c6eb6c73762589a07fb(0-2). Message: System.Net.WebException: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ) ---> System.Net.Sockets.SocketException: 無法連線，因為目標電腦拒絕連線。    at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0016d] in <735c83e43c004ee998f77c68cf8035da>:0     --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0003a] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <599589bf4ce248909b8a14cbe4a2034e>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<GetResponseAsync>d__39.MoveNext () [0x00086] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<SendAsync>d__36.MoveNext () [0x0017d] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.TransmissionSender+<StartSending>d__24.MoveNext () [0x000bb] in <20f93252061247f09e8451bed298b761>:0 . 
2020-08-13T11:34:34.9061570+08:00|366|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: e8b306d171dd4c6eb6c73762589a07fb(0-2). Message: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ). StatusCode: 0. Description: . 
2020-08-13T11:34:34.9231115+08:00|366|WARN|DataSync.Log|SenderEnqueueNoCapacity. TransmissionCount: 0. Capacity: 0. 
2020-08-13T11:39:08.3459148+08:00|1|INFO|DataSync.Log|Storage folder: D:\Projects\BuildCube\BuildCube\Assets\TestData\TestStore successfully validated. 
2020-08-13T11:39:08.3917919+08:00|324|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2020-08-13T11:39:08.4631082+08:00|324|INFO|DataSync.Log|MovedFromStorageToSender. 
2020-08-13T11:39:08.5339190+08:00|324|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2020-08-13T11:39:08.6129388+08:00|324|INFO|DataSync.Log|MovedFromBufferToSender. 
2020-08-13T11:39:21.5115432+08:00|1|INFO|DataSync.Log|Transmitter flushed telemetry events. 
2020-08-13T11:39:21.5334839+08:00|1|INFO|DataSync.Log|SerializationStarted. Items count: 3 
2020-08-13T11:39:21.5793611+08:00|1|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: 7099ce6b85a34d679cdc28d6ef4111e0(0-2). 
2020-08-13T11:39:21.6013031+08:00|1|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: 7099ce6b85a34d679cdc28d6ef4111e0(0-2). 
2020-08-13T11:39:21.6431912+08:00|1|INFO|DataSync.Log|DataSync.ApplicationLifecycleTransmissionPolicy changed sender capacity to 0 
2020-08-13T11:39:21.6571539+08:00|1|INFO|DataSync.Log|DataSync.ApplicationLifecycleTransmissionPolicy changed buffer capacity to 0 
2020-08-13T11:39:21.6805996+08:00|1|INFO|DataSync.Log|StorageCapacityReset: DataSync.ApplicationLifecycleTransmissionPolicy 
2020-08-13T11:39:21.6885785+08:00|1|WARN|DataSync.Log|BufferEnqueueNoCapacity. Size: 0. Capacity: 0. 
2020-08-13T11:39:21.7015438+08:00|1|INFO|DataSync.Log|MovedFromBufferToStorage. 
2020-08-13T11:39:21.7015438+08:00|1|INFO|DataSync.Log|TransmitterEmptyBuffer 
2020-08-13T11:39:21.7015438+08:00|1|WARN|DataSync.Log|BufferEnqueueNoCapacity. Size: 0. Capacity: 0. 
2020-08-13T11:39:24.6986236+08:00|381|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 7099ce6b85a34d679cdc28d6ef4111e0(0-2). Message: System.Net.WebException: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ) ---> System.Net.Sockets.SocketException: 無法連線，因為目標電腦拒絕連線。    at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0016d] in <735c83e43c004ee998f77c68cf8035da>:0     --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0003a] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <599589bf4ce248909b8a14cbe4a2034e>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<GetResponseAsync>d__39.MoveNext () [0x00086] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<SendAsync>d__36.MoveNext () [0x0017d] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.TransmissionSender+<StartSending>d__24.MoveNext () [0x000bb] in <20f93252061247f09e8451bed298b761>:0 . 
2020-08-13T11:39:24.7105921+08:00|381|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 7099ce6b85a34d679cdc28d6ef4111e0(0-2). Message: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ). StatusCode: 0. Description: . 
2020-08-13T11:39:24.7285456+08:00|381|WARN|DataSync.Log|SenderEnqueueNoCapacity. TransmissionCount: 0. Capacity: 0. 
2020-08-13T11:54:34.5777747+08:00|1|INFO|DataSync.Log|Storage folder: D:\Projects\BuildCube\BuildCube\Assets\TestData\TestStore successfully validated. 
2020-08-13T11:54:34.6196630+08:00|382|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2020-08-13T11:54:34.6849971+08:00|382|INFO|DataSync.Log|MovedFromStorageToSender. 
2020-08-13T11:54:34.7553861+08:00|382|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2020-08-13T11:54:34.8231365+08:00|382|INFO|DataSync.Log|MovedFromBufferToSender. 
2020-08-13T11:55:04.6389523+08:00|381|INFO|DataSync.Log|SerializationStarted. Items count: 1 
2020-08-13T11:55:04.7416781+08:00|381|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: 218b4844f21e4c9c8a23ccd2a2e44996(0-0). 
2020-08-13T11:55:04.7676089+08:00|381|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: 218b4844f21e4c9c8a23ccd2a2e44996(0-0). 
2020-08-13T11:55:07.9792348+08:00|382|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 218b4844f21e4c9c8a23ccd2a2e44996(0-0). Message: System.Net.WebException: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ) ---> System.Net.Sockets.SocketException: 無法連線，因為目標電腦拒絕連線。    at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0016d] in <735c83e43c004ee998f77c68cf8035da>:0     --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0003a] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <599589bf4ce248909b8a14cbe4a2034e>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<GetResponseAsync>d__39.MoveNext () [0x00086] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<SendAsync>d__36.MoveNext () [0x0017d] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.TransmissionSender+<StartSending>d__24.MoveNext () [0x000bb] in <20f93252061247f09e8451bed298b761>:0 . 
2020-08-13T11:55:08.0031707+08:00|382|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 218b4844f21e4c9c8a23ccd2a2e44996(0-0). Message: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ). StatusCode: 0. Description: . 
2020-08-13T11:55:16.1743052+08:00|1|INFO|DataSync.Log|Transmitter flushed telemetry events. 
2020-08-13T11:55:16.1882686+08:00|1|INFO|DataSync.Log|SerializationStarted. Items count: 2 
2020-08-13T11:55:16.2032276+08:00|1|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: 759a7446b8ee456ca09b1db2011e976a(1-2). 
2020-08-13T11:55:16.2032276+08:00|1|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: 759a7446b8ee456ca09b1db2011e976a(1-2). 
2020-08-13T11:55:16.2311540+08:00|1|INFO|DataSync.Log|DataSync.ApplicationLifecycleTransmissionPolicy changed sender capacity to 0 
2020-08-13T11:55:16.2481080+08:00|1|INFO|DataSync.Log|DataSync.ApplicationLifecycleTransmissionPolicy changed buffer capacity to 0 
2020-08-13T11:55:16.2481080+08:00|1|INFO|DataSync.Log|StorageCapacityReset: DataSync.ApplicationLifecycleTransmissionPolicy 
2020-08-13T11:55:16.2780419+08:00|1|WARN|DataSync.Log|BufferEnqueueNoCapacity. Size: 0. Capacity: 0. 
2020-08-13T11:55:16.2860064+08:00|1|INFO|DataSync.Log|MovedFromBufferToStorage. 
2020-08-13T11:55:16.3029619+08:00|1|INFO|DataSync.Log|TransmitterEmptyBuffer 
2020-08-13T11:55:16.3159274+08:00|1|WARN|DataSync.Log|BufferEnqueueNoCapacity. Size: 0. Capacity: 0. 
2020-08-13T11:55:19.2693456+08:00|285|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 759a7446b8ee456ca09b1db2011e976a(1-2). Message: System.Net.WebException: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ) ---> System.Net.Sockets.SocketException: 無法連線，因為目標電腦拒絕連線。    at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0016d] in <735c83e43c004ee998f77c68cf8035da>:0     --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0003a] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <599589bf4ce248909b8a14cbe4a2034e>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<GetResponseAsync>d__39.MoveNext () [0x00086] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<SendAsync>d__36.MoveNext () [0x0017d] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.TransmissionSender+<StartSending>d__24.MoveNext () [0x000bb] in <20f93252061247f09e8451bed298b761>:0 . 
2020-08-13T11:55:19.2693456+08:00|285|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 759a7446b8ee456ca09b1db2011e976a(1-2). Message: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ). StatusCode: 0. Description: . 
2020-08-13T11:55:19.2942789+08:00|285|WARN|DataSync.Log|SenderEnqueueNoCapacity. TransmissionCount: 0. Capacity: 0. 
2020-08-13T11:58:34.6754408+08:00|1|INFO|DataSync.Log|Storage folder: D:\Projects\BuildCube\BuildCube\Assets\TestData\TestStore successfully validated. 
2020-08-13T11:58:34.7143378+08:00|285|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2020-08-13T11:58:34.7841509+08:00|285|INFO|DataSync.Log|MovedFromStorageToSender. 
2020-08-13T11:58:34.8589514+08:00|285|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2020-08-13T11:58:34.9187911+08:00|285|INFO|DataSync.Log|MovedFromBufferToSender. 
2020-08-13T11:59:04.7278105+08:00|366|INFO|DataSync.Log|SerializationStarted. Items count: 1 
2020-08-13T11:59:04.8265409+08:00|366|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: 5405d5f8ff4f4190a0713f7606414048(0-0). 
2020-08-13T11:59:04.8464879+08:00|366|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: 5405d5f8ff4f4190a0713f7606414048(0-0). 
2020-08-13T11:59:08.0453788+08:00|365|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 5405d5f8ff4f4190a0713f7606414048(0-0). Message: System.Net.WebException: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ) ---> System.Net.Sockets.SocketException: 無法連線，因為目標電腦拒絕連線。    at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0016d] in <735c83e43c004ee998f77c68cf8035da>:0     --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0003a] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <599589bf4ce248909b8a14cbe4a2034e>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<GetResponseAsync>d__39.MoveNext () [0x00086] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<SendAsync>d__36.MoveNext () [0x0017d] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.TransmissionSender+<StartSending>d__24.MoveNext () [0x000bb] in <20f93252061247f09e8451bed298b761>:0 . 
2020-08-13T11:59:08.0453788+08:00|365|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 5405d5f8ff4f4190a0713f7606414048(0-0). Message: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ). StatusCode: 0. Description: . 
2020-08-13T11:59:59.4825935+08:00|1|INFO|DataSync.Log|Storage folder: D:\Projects\BuildCube\BuildCube\Assets\TestData\TestStore successfully validated. 
2020-08-13T11:59:59.5264478+08:00|285|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2020-08-13T11:59:59.6012474+08:00|285|INFO|DataSync.Log|MovedFromStorageToSender. 
2020-08-13T11:59:59.6742078+08:00|285|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2020-08-13T11:59:59.7385422+08:00|285|INFO|DataSync.Log|MovedFromBufferToSender. 
2020-08-13T12:00:24.3425379+08:00|1|INFO|DataSync.Log|Storage folder: D:\Projects\BuildCube\BuildCube\Assets\TestData\TestStore successfully validated. 
2020-08-13T12:00:24.3784420+08:00|44|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2020-08-13T12:00:24.4432685+08:00|44|INFO|DataSync.Log|MovedFromStorageToSender. 
2020-08-13T12:00:24.5031136+08:00|44|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2020-08-13T12:00:24.5623535+08:00|44|INFO|DataSync.Log|MovedFromBufferToSender. 
2020-08-13T12:01:03.1786063+08:00|1|INFO|DataSync.Log|Storage folder: D:\Projects\BuildCube\BuildCube\Assets\TestData\TestStore successfully validated. 
2020-08-13T12:01:03.2175030+08:00|382|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2020-08-13T12:01:03.2843246+08:00|382|INFO|DataSync.Log|MovedFromStorageToSender. 
2020-08-13T12:01:03.3641106+08:00|382|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2020-08-13T12:01:03.4274501+08:00|382|INFO|DataSync.Log|MovedFromBufferToSender. 
2020-08-13T12:01:33.2312757+08:00|365|INFO|DataSync.Log|SerializationStarted. Items count: 1 
2020-08-13T12:01:33.3220332+08:00|365|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: cd2b3296f450460f83e15f477dbdf2c4(0-0). 
2020-08-13T12:01:33.3419810+08:00|365|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: cd2b3296f450460f83e15f477dbdf2c4(0-0). 
2020-08-13T12:02:01.0927709+08:00|1|INFO|DataSync.Log|Storage folder: D:\Projects\BuildCube\BuildCube\Assets\TestData\TestStore successfully validated. 
2020-08-13T12:02:01.1336619+08:00|45|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2020-08-13T12:02:01.2149551+08:00|45|INFO|DataSync.Log|MovedFromStorageToSender. 
2020-08-13T12:02:01.2937448+08:00|45|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2020-08-13T12:02:01.3595683+08:00|45|INFO|DataSync.Log|MovedFromBufferToSender. 
2020-08-13T12:02:31.1475990+08:00|383|INFO|DataSync.Log|SerializationStarted. Items count: 1 
2020-08-13T12:02:31.2493277+08:00|383|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: 10c740621ad646a08b14d13c0baf0da6(0-0). 
2020-08-13T12:02:31.2852309+08:00|383|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: 10c740621ad646a08b14d13c0baf0da6(0-0). 
2020-08-13T12:02:34.5528016+08:00|365|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 10c740621ad646a08b14d13c0baf0da6(0-0). Message: System.Net.WebException: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ) ---> System.Net.Sockets.SocketException: 無法連線，因為目標電腦拒絕連線。    at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0016d] in <735c83e43c004ee998f77c68cf8035da>:0     --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0003a] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <599589bf4ce248909b8a14cbe4a2034e>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<GetResponseAsync>d__39.MoveNext () [0x00086] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<SendAsync>d__36.MoveNext () [0x0017d] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.TransmissionSender+<StartSending>d__24.MoveNext () [0x000bb] in <20f93252061247f09e8451bed298b761>:0 . 
2020-08-13T12:02:34.5667639+08:00|365|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 10c740621ad646a08b14d13c0baf0da6(0-0). Message: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ). StatusCode: 0. Description: . 
2020-08-13T12:02:46.8486319+08:00|1|INFO|DataSync.Log|Transmitter flushed telemetry events. 
2020-08-13T12:02:46.8625950+08:00|1|INFO|DataSync.Log|SerializationStarted. Items count: 2 
2020-08-13T12:02:46.8765581+08:00|1|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: c814838dbfd749819bd962ff1e42c485(1-2). 
2020-08-13T12:02:46.8905196+08:00|1|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: c814838dbfd749819bd962ff1e42c485(1-2). 
2020-08-13T12:02:46.9044831+08:00|1|INFO|DataSync.Log|DataSync.ApplicationLifecycleTransmissionPolicy changed sender capacity to 0 
2020-08-13T12:02:46.9044831+08:00|1|INFO|DataSync.Log|DataSync.ApplicationLifecycleTransmissionPolicy changed buffer capacity to 0 
2020-08-13T12:02:46.9383923+08:00|1|INFO|DataSync.Log|StorageCapacityReset: DataSync.ApplicationLifecycleTransmissionPolicy 
2020-08-13T12:02:46.9383923+08:00|1|WARN|DataSync.Log|BufferEnqueueNoCapacity. Size: 0. Capacity: 0. 
2020-08-13T12:02:46.9673156+08:00|1|INFO|DataSync.Log|MovedFromBufferToStorage. 
2020-08-13T12:02:46.9912512+08:00|1|INFO|DataSync.Log|TransmitterEmptyBuffer 
2020-08-13T12:02:47.0032188+08:00|1|WARN|DataSync.Log|BufferEnqueueNoCapacity. Size: 0. Capacity: 0. 
2020-08-13T12:02:49.9940714+08:00|285|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: c814838dbfd749819bd962ff1e42c485(1-2). Message: System.Net.WebException: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ) ---> System.Net.Sockets.SocketException: 無法連線，因為目標電腦拒絕連線。    at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0016d] in <735c83e43c004ee998f77c68cf8035da>:0     --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0003a] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <599589bf4ce248909b8a14cbe4a2034e>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<GetResponseAsync>d__39.MoveNext () [0x00086] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<SendAsync>d__36.MoveNext () [0x0017d] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.TransmissionSender+<StartSending>d__24.MoveNext () [0x000bb] in <20f93252061247f09e8451bed298b761>:0 . 
2020-08-13T12:02:50.0030470+08:00|285|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: c814838dbfd749819bd962ff1e42c485(1-2). Message: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ). StatusCode: 0. Description: . 
2020-08-13T12:02:50.0160132+08:00|285|WARN|DataSync.Log|SenderEnqueueNoCapacity. TransmissionCount: 0. Capacity: 0. 
